# Generated by Django 4.1.7 on 2023-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("actors", models.CharField(max_length=100)),
                ("plot", models.CharField(max_length=100)),
                ("poster", models.CharField(max_length=100)),
                ("imdb_rating", models.CharField(max_length=100)),
                ("imdb_votes", models.CharField(max_length=100)),
                ("imdb_id", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("dvd", models.CharField(max_length=100)),
                ("box_office", models.CharField(max_length=100)),
                ("production", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
                ("response", models.CharField(max_length=100)),
            ],
        ),
    ]
