# Generated by Django 4.1.7 on 2023-04-02 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Movies_Library_APP", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="box_office",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="dvd",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdb_id",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdb_rating",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdb_votes",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="plot",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="production",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="response",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="type",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="website",
        ),
    ]
